jobs:
- name: job-hooks
  plan:
  - task: task-success
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: alpine
          tag: latest
      run:
        path: echo
        args: ["Task Succeeded!"]
  - task: task-failed
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: alpine
          tag: latest
      run:
        path: echo
        args: ["Task Failed!"]