task-common-config: &task-config
  platform: linux
  image_resource: ((hook.source.image))

resources:
- name: concourse-tutorials
  type: git
  source: ((concourse.git))
- name: python-scripts
  type: git
  source:
    uri: https://github.com/kurmivivek295/python-scripts.git
    branch: develop

jobs:
- name: job-hooks
  plan:
  - get: concourse-tutorials
  - get: python-scripts
  - task: task-params
    file: concourse-tutorials/lab-4.3/task_run.yml
    params:
      FILE_NAME: ((filename))
  on_success:
    task: job-successful
    config:
      <<: *task-config
      run:
        path: echo
        args: ["Job Done!"]
  on_failure:
    task: job-failure
    config:
      <<: *task-config
      run:
        path: echo
        args: ["Job Failed!"]    