---
resources:
# to get the task file
- name: concourse-tutorials
  type: git
  source:
    uri: https://github.com/kurmivivek295/concourse-tutorials.git
    branch: master

# to get the application file from your repository
- name: python-scripts
  type: git 
  source:
    uri: https://github.com/kurmivivek295/python-scripts.git 
    branch: develop # specify the branch here to work with

jobs:
- name: job-io
  public: true
  plan:
  - get: concourse-tutorials
  - get: python-scripts
  - task: task-io
    file: concourse-tutorials/lab-4.5/task_run.yml
    params:
      FILE_NAME: ((filename))
  - task: task-cat
    file: concourse-tutorials/lab-4.5/task_cat.yml