---
jobs:
- name: job-hello-world
  plan:
  - task: task-hello-world
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: alpine, tag: latest}
      run:
        path: echo
        args: ["Hello, world!"]